# Generated by Django 6.0.6 on 2026-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='encrypted_files/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('iv', models.CharField(max_length=100)),
                ('salt', models.CharField(blank=True, max_length=100, null=True)),
                ('wrap_iv', models.CharField(blank=True, max_length=100, null=True)),
                ('wrapped_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('self_destruct', models.BooleanField(default=False)),
                ('download_limit', models.IntegerField(default=1)),
                ('download_count', models.IntegerField(default=0)),
            ],
        ),
    ]
