# Generated by Django 6.0.6 on 2026-06-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('chunk_size', models.IntegerField(default=524288)),
                ('total_chunks', models.IntegerField(default=1)),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('salt', models.CharField(blank=True, max_length=200, null=True)),
                ('wrap_iv', models.CharField(blank=True, max_length=100, null=True)),
                ('wrapped_key', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('self_destruct', models.BooleanField(default=False)),
                ('download_limit', models.IntegerField(default=1)),
                ('download_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransferChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('iv', models.CharField(max_length=100)),
                ('data', models.FileField(upload_to='chunks/')),
                ('original_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.transfer')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('transfer', 'seq')},
            },
        ),
        migrations.DeleteModel(
            name='EncryptedFile',
        ),
    ]
