# Generated by Django 6.0.7 on 2026-07-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transfer_download_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCRoom',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WebRTCSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='api.webrtcroom')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
